### ISSUE TITLE
Doesn't build on zig 0.15.2

### ISSUE THREAD

**Issue by Zorgatone** [thechampagne/webview-zig#14]
```
> zig build run --summary all
/Users/zorgatone/.cache/zig/p/webview-0.1.0-ImQK_yb6IADsgQL8f72LGd4xkaSrxqQn9RyYy3U36s1J/build.zig:50:24: error: no field or member function named 'addStaticLibrary' in 'Build'
    const staticLib = b.addStaticLibrary(.{
                      ~^~~~~~~~~~~~~~~~~
/Users/zorgatone/.local/share/zigup/0.15.2/files/lib/std/Build.zig:1:1: note: struct declared here
const std = @import("std.zig");
^~~~~
/Users/zorgatone/.cache/zig/p/webview-0.1.0-ImQK_yb6IADsgQL8f72LGd4xkaSrxqQn9RyYy3U36s1J/build.zig:50:24: note: method invocation only supports up to one level of implicit pointer dereferencing
/Users/zorgatone/.cache/zig/p/webview-0.1.0-ImQK_yb6IADsgQL8f72LGd4xkaSrxqQn9RyYy3U36s1J/build.zig:50:24: note: use '.*' to dereference pointer
referenced by:
    runBuild__anon_73950: /Users/zorgatone/.local/share/zigup/0.15.2/files/lib/std/Build.zig:2214:33
    dependencyInner__anon_71347: /Users/zorgatone/.local/share/zigup/0.15.2/files/lib/std/Build.zig:2195:29
    8 reference(s) hidden; use '-freference-trace=10' to see all references
```
